### ISSUE TITLE
failed to install pinned version on version change

### ISSUE THREAD

**Issue by vkhatri** [vkhatri/chef-topbeat#18]
``` shell
         * yum_package[topbeat] action install

           ================================================================================
           Error executing action `install` on resource 'yum_package[topbeat]'
           ================================================================================

           Chef::Exceptions::Package
           -------------------------
           Version 1.2.3-1 of topbeat not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/topbeat/recipes/install.rb

            58: package 'topbeat' do
            59:   version version_string
            60:   options node['platform_family'] == 'rhel' ? '' : '-o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"'
            61:   allow_downgrade true if node['platform_family'] == 'rhel'
            62: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/topbeat/recipes/install.rb:58:in `from_file'

           yum_package("topbeat") do
             package_name "topbeat"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "topbeat"
             recipe_name "install"
             version "1.2.3-1"
             allow_downgrade true
             flush_cache {:before=>false, :after=>false}
           end

           Platform:
           ---------
           x86_64-linux


       Running handlers:
       [2016-09-11T08:38:58+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-09-11T08:38:58+00:00] ERROR: Exception handlers complete
       Chef Client failed. 2 resources updated in 04 seconds
       [2016-09-11T08:38:58+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-09-11T08:38:58+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-09-11T08:38:58+00:00] ERROR: yum_package[topbeat] (topbeat::install line 58) had an error: Chef::Exceptions::Package: Version 1.2.3-1 of topbeat not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)
       [2016-09-11T08:38:58+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-centos-68>.  Please see .kitchen/logs/default-centos-68.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by vkhatri** [comment]
However, second chef run is able to install the pinned version. Installing package manually works ok.
